services:
  api:
    image: "auth_ready:latest"
    container_name: example_app_api
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=postgres
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: uvicorn main:app --host 0.0.0.0 --port 80
    networks:
      - app-network

  postgres:
    image: "postgres:alpine"
    container_name: "postgres_db"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_uptime:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_uptime: