"""create_ursers_urls_db

Revision ID: be90df8d49b7
Revises: 3d86036a686e
Create Date: 2026-03-17 12:24:57.247141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be90df8d49b7'
down_revision: Union[str, None] = '3d86036a686e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_urls',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url'], ['urls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_urls')
    # ### end Alembic commands ###
